transformations:
  - frame_id: camera_color_optical_frame
    id: charger
    transform:
      - 0.887
      - 0.040
      - 0.848
      - -0.065
      - 0.873
      - 0.061
      - -0.480
  - frame_id: zed_doorway_left_camera_frame
    id: tag_38_zed
    transform:
      - 1.915
      - 1.500
      - 0.320
      - -0.229
      - 0.199
      - 0.825
      - -0.477

  - frame_id: zed_kitchen_left_camera_frame
    id: tag_44_zed
    transform:
      - 1.259
      - 0.990
      - 0.625
      - 0.178
      - -0.150
      - -0.754
      - 0.615
