transformations:
  - frame_id: camera_color_optical_frame
    id: charger
    transform:
      - 0.826
      - 0.047
      - 0.910
      - -0.126
      - 0.879
      - 0.088
      - -0.451
  - frame_id: zed_dining_room_left_camera_frame
    id: tag_37_zed
    transform:
      - 1.915
      - 1.500
      - 0.320
      - -0.229
      - 0.199
      - 0.825
      - -0.477
  - frame_id: zed_doorway_left_camera_frame
    id: tag_38_zed
    transform:
      - 1.703
      - -0.802
      - 0.533
      - -0.266
      - 0.080
      - 0.782
      - 0.558
  - frame_id: zed_kitchen_left_camera_frame
    id: tag_44_zed
    transform:
      - 1.259
      - 0.990
      - 0.625
      - 0.178
      - -0.150
      - -0.754
      - 0.615
