transformations:
  - frame_id: base_link
    id: camera_color_optical_frame
    transform:
      - 0.000
      - 0.000
      - 0.500
      - 0.500
      - -0.500
      - 0.500
      - -0.500
  - frame_id: charger
    id: camera_color_optical_frame
    transform:
      - -0.312
      - -0.040
      - 0.188
      - 0.500
      - -0.500
      - 0.500
      - -0.500
  - frame_id: zed_dining_room_left_camera_frame
    id: tag_37_zed
    transform:
      - 1.915
      - 1.500
      - 0.320
      - -0.229
      - 0.199
      - 0.825
      - -0.477
  - frame_id: zed_doorway_left_camera_frame
    id: tag_38_zed
    transform:
      - 1.703
      - -0.802
      - 0.533
      - -0.266
      - 0.080
      - 0.782
      - 0.558
  - frame_id: zed_kitchen_left_camera_frame
    id: tag_44_zed
    transform:
      - 1.259
      - 0.990
      - 0.625
      - 0.178
      - -0.150
      - -0.754
      - 0.615
#  ros2 run tf2_ros tf2_echo unity zed_cam__
  - frame_id: unity
    id: zed_doorway_cam
    transform:
      - -3.376
      - 0.489
      - 0.680
      - -0.006
      - 0.043
      - 0.168
      - 0.985
