transformations:
- frame_id: unity
  id: map
  transform:
  - 0.024893627745885334
  - 0.006889205892561369
  - -1.1144409131615398
  - 2.2934993529623165e-16
  - -8.565181907303272e-19
  - 0.003734521297439247
  - 0.9999930266510257
- frame_id: unity
  id: bedroom
  transform:
  - -1.7000000476837158
  - -0.12999999523162842
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: door
  transform:
  - 3.1500000953674316
  - 4.380000114440918
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: outside
  transform:
  - 4.329999923706055
  - 4.579999923706055
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: living_room
  transform:
  - 1.350000023841858
  - -0.12999999523162842
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: kitchen
  transform:
  - 0.8100000023841858
  - 4.429999828338623
  - 0.8899999856948853
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: bathroom
  transform:
  - -0.14000000059604645
  - -0.1899999976158142
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: dining_room
  transform:
  - -0.9900000095367432
  - 4.510000228881836
  - -1.1371086835861206
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: home
  transform:
  - 1.3600000143051147
  - 0.6200000047683716
  - -0.23000000417232513
  - 0.0
  - 0.0
  - 0.0
  - 1.0
