transformations:
- frame_id: unity
  id: aptag_0
  transform:
  - -0.1289999932050705
  - -1.5809999704360962
  - -0.8669999837875366
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: aptag_2
  transform:
  - -0.41600000858306885
  - -0.6100000143051147
  - -0.7160000205039978
  - 0.0
  - 0.0
  - 0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_3
  transform:
  - 0.49900001287460327
  - 4.27400016784668
  - -0.7250000238418579
  - 0.0
  - 0.0
  - -0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_4
  transform:
  - -0.46700000762939453
  - 2.0230000019073486
  - -0.8429999947547913
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: aptag_6
  transform:
  - -1.4550000429153442
  - 3.7699999809265137
  - -0.7670000195503235
  - 0.0
  - 0.0
  - 0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_7
  transform:
  - 0.06800000369548798
  - 5.593999862670898
  - -0.7039999961853027
  - 0.0
  - 0.0
  - 1.0
  - 0.0
- frame_id: unity
  id: aptag_8
  transform:
  - 1.562999963760376
  - -3.0239999294281006
  - -0.7409999966621399
  - 0.0
  - 0.0
  - -0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_9
  transform:
  - -1.0130000114440918
  - -6.304500102996826
  - -0.6887000203132629
  - 0.0
  - 0.0
  - 0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_10
  transform:
  - 0.1599999964237213
  - -6.257599830627441
  - -0.6869999766349792
  - 0.0
  - 0.0
  - 0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_11
  transform:
  - 2.191999912261963
  - -5.4019999504089355
  - -0.9419999718666077
  - 0.0
  - 0.0
  - 1.0
  - 0.0
- frame_id: unity
  id: aptag_12
  transform:
  - 2.177999973297119
  - -4.242000102996826
  - -0.9369999766349792
  - 0.0
  - 0.0
  - 1.0
  - 0.0
- frame_id: unity
  id: aptag_13
  transform:
  - -3.6700000762939453
  - -4.328999996185303
  - -0.367000013589859
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: aptag_14
  transform:
  - -2.8259999752044678
  - -3.2049999237060547
  - -0.7670000195503235
  - 0.0
  - 0.0
  - -0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_15
  transform:
  - 2.056999921798706
  - -1.2230000495910645
  - -0.8690000176429749
  - 0.0
  - 0.0
  - 1.0
  - 0.0
- frame_id: unity
  id: aptag_29
  transform:
  - -0.09570000320672989
  - -2.7139999866485596
  - -0.7870000004768372
  - 0.0
  - 0.0
  - 0.0
  - 1.0
- frame_id: unity
  id: aptag_37
  transform:
  - 1.850000023841858
  - 1.25
  - 0.1550000011920929
  - 0.0
  - 0.0
  - 0.7071067811865475
  - 0.7071067811865476
- frame_id: unity
  id: aptag_38
  transform:
    - -2.0850000381469727
    - 1.50600004196167
    - 0.4309999942779541
    - 0.0
    - 0.0
    - 0.9999558021208489
    - 0.009401797958351455
- frame_id: unity
  id: aptag_44
  transform:
  - -0.11999999731779099
  - -1.899999976158142
  - 0.6890000104904175
  - 0.0
  - 0.0
  - 0.0
  - 1.0
